# Generated by Django 3.2.9 on 2021-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='slug'),
        ),
    ]
