# Generated by Django 3.2.9 on 2021-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
