# Generated by Django 3.2.9 on 2021-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=255, null=True, verbose_name='address2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='work_address',
            field=models.BooleanField(null=True, verbose_name='work address'),
        ),
    ]
