# Generated by Django 3.2.9 on 2021-11-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
